### ISSUE TITLE
Preprocessing step not calling out missing required field

### ISSUE THREAD

**Issue by meganforbes** [collectionspace/cspace-batch-import#49]
Preprocessing not providing any error/warning/message on a CSV with a required value missing in a single cell - see attached file for example.

[CSV Import Test 2b no id number.csv](https://github.com/collectionspace/cspace-batch-import/files/6312799/CSV.Import.Test.2b.no.id.number.csv)

**Comment by meganforbes** [comment]
Potential second issue w/this same file - Processing step shows 1 warning, no errors, downloaded file (attached) calls the issue an ERROR but message is hard for an end user to parse: 

Mapper did not return   result: undefined method `text' for nil:NilClass --   /app/vendor/bundle/ruby/2.7.0/bundler/gems/collectionspace-mapper-0df8b8559ddf/lib/collectionspace/mapper/data_mapper.rb:33:in   `set_response_identifier'
--


[mf-test-0414-no-id-single-field-20210414-1832_processing_report.csv](https://github.com/collectionspace/cspace-batch-import/files/6312991/mf-test-0414-no-id-single-field-20210414-1832_processing_report.csv)

**Comment by kspurgin** [comment]
@meganforbes - That's because this situation wasn't supposed to be allowed (get to processing step while missing required fields)

I will make the handling of this more graceful, since weird exceptions always end up sneaking through.

It is possible in the situation of the mapper-under-the-hood barfing unexpectedly to put a value in the `ERR: mapper` column more like: "Mapper did not return result for unexpected reason: please send a copy of this report to supportemailhere and you may disregard the following helpful info for diagnosing this problem: insert nasty technical/code specific stuff here"

I do want to retain the nasty technical/code specific stuff, though, because it may help determine what a weird problem was, even if trying the same process myself doesn't get the same error. 

Still on my list to write up the fuller "Errors/warnings you may see in your reports" documentation.
